### ISSUE TITLE
Allow angular 14 as peer dependency.

### ISSUE THREAD

**Issue by oz-d3v** [ngx-api-utils/ngx-api-utils#74]
Allow angular 14 as peer dependency.

**Comment by martin31821** [comment]
adding to the same, would be good to go up to ng 17 and also flag the library as ivy-compatible.

**Comment by smoke** [comment]
@martin31821 The 1.0.12 adds wildcard for the version, does this work for ng 17? Can you help me how to flag the library as ivy-compatible?

**Comment by smoke** [comment]
the issue should be resolved with >=[1.0.12](https://github.com/ngx-api-utils/ngx-api-utils/releases/tag/1.0.12)
